version: "3.9"

services:
  red_tetris:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8443:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
